#lang pollen

◊(define-meta title "Preface to the Second and Revised Edition")
◊(define-meta author "Edwin Abbot")

◊newthought{If my} poor Flatland friend retained the vigour of mind which he enjoyed when he began to compose these Memoirs, I should not now need to represent him in this preface, in which he desires, firstly, to return his thanks to his readers and critics in Spaceland, whose appreciation has, with unexpected celerity, required a second edition of his work; secondly, to apologize forcertain errors and misprints (for which, however, he is not entirely responsible); and, thirdly, to explain one or two misconceptions. But he is not the Square he once was. Years of imprisonment, and the still heavier burden of general incredulity and mockery, have combined with the natural decay of old age to erase from his mind many of the thoughts and notions, and much also of the terminology, which he acquired during his short stay in Spaceland. He has, therefore, requested me to reply in his behalf to two special objections, one of an intellectual, the other of a moral nature.

The first objection is, that a Flatlander, seeing a Line, sees something that must be thick to the eye as well as long to the eye (otherwise it would not be visible, if it had not some thickness); and consequently he ought (it is argued) to acknowledge that his countrymen are not only long and broad, but also (though doubtless in a very slight degree) thick or high. His objection is plausible, and, to Spacelanders, almost irresistible, so that, I confess, when I first heard it, I knew not what to reply. But my poor old friend's answer appears to me completely to meet it.

"I admit," said he --- when I mentioned to him this objection --- "I admit the truth of your critic's facts, but I deny his conclusions. It is true that we have really in Flatland a Third unrecognized Dimension called `height,' just as it is also true that you have really in Spaceland a Fourth unrecognized Dimension, called by no name at present, but which I will call 'extra-height'. But we can no more take cognizance of our 'height' then you can of your 'extra-height'. Even I --- who have been in Spaceland, and have had the privilege of understanding for twenty-four hours the meaning of 'height' --- even I cannot now comprehend it, nor realize it by the sense of sight or by any process of reason; I can but apprehend it by faith.

"The reason is obvious. Dimension implies direction, implies measurement, implies the more and the less. Now, all our lines are equally and infinitesimally thick (or high, whichever you like); consequently, there is nothing in them to lead our minds to the conception of that Dimension. No 'delicate micrometer' --- as has been suggested by one too hasty Spaceland critic --- would in the least avail us; for we should not know what to measure, nor in what direction. When we see a Line, we see something that is long and bright; brightness, as well as length, is necessary to the existence of a Line; if the brightness vanishes, the Line is extinguished. Hence, all my Flatland friends --- when I talk to them about the unrecognized Dimension which is somehow visible in a Line --- say, 'Ah, you mean brightness': and when I reply, 'No, I mean a real Dimension,' they at once retort 'Then measure it, or tell us in what direction it extends'; and this silences me, for I can do neither. Only yesterday, when the Chief Circle (in other words our High Priest) came to inspect the State Prison and paid me his seventh annual visit, and when for the seventh time he put me the question, 'Was I any better?' I tried to prove to him that he was 'high,' as well as long and broad, although he did not know it. But what was his reply? 'You say I am "high"; measure my "highness" and I will believe you.' What could I do? How could I meet his challenge? I was crushed; and he left the room triumphant.

"Does this still seem strange to you? Then put yourself in a similar position. Suppose a person of the Fourth Dimension, condescending to visit you, were to say, 'Whenever you open your eyes, you see a Plane (which is of Two Dimensions) and you infer a Solid (which is of Three); but in reality you also see (though you do not recognize) a Fourth Dimension, which is not colour nor brightness nor anything of the kind, but a true Dimension, although I cannot point out to you its direction, nor can you possibly measure it.' What would you say to such a visitor? Would not you have him locked up? Well, that is my fate: and it is as natural for us Flatlanders to lock up a Square for preaching the Third Dimension, as it is for you Spacelanders to lock up a Cube for preaching the Fourth. Alas, how strong a family likeness runs through blind and persecuting humanity in all Dimensions! Points, Lines, Squares, Cubes, Extra-Cubes --- we are all liable to the same errors, all alike the Slaves of our respective Dimensional prejudices, as one of your Spaceland poets has said◊numbered-note{The Author desires me to add, that the misconception of some of his critics on this matter has induced him to insert in his dialogue with the Sphere, certain remarks which have a bearing on the point in question, and which he had previously omitted as being tedious and unnecessary.} ---

◊blockquote{◊p{One touch of Nature makes all worlds akin.}}

On this, point the defence of the Square seems to me to be impregnable. I wish I could say that his answer to the second (or moral) objection was equally clear and cogent. lt has been objected that he is a woman-hater; and as this objection has been vehemently urged by those whom Nature's decree has constituted the somewhat larger half of the Spaceland race, I should like to remove it, so far as I can honestly do so. But the Square is so unaccustomed to the use of the moral terminology of Spaceland that I should be doing him an injustice if I were literally to transcribe his defence against this charge. Acting, therefore, as his interpreter and summarizer, I gather that in the course of an imprisonment of seven years he has himself modified his own personal views, both as regards Women and as regards the Isosceles or Lower Classes. Personally, he now inclines to the opinion of the Sphere that the Straight Lines are in many important respects superior to the Circles. But, writing as a Historian, he has identified himself (perhaps too closely) with the views generally adopted by Flatland, and (as he has been informed) even Spaceland, Historians; in whose pages (until very recent times) the destinies of Women and of the masses of mankind have seldom been deemed worthy of mention and never of careful consideration.

In a still more obscure passage he now desires to disavow the Circular or aristocratic tendencies with which some critics have naturally credited him. While doing justice to the intellectual power with which a few Circles for many generations maintained their supremacy over immense multitudes of their countrymen, he believes that the facts of Flatland, speaking for themselves without comment On his part, declare that Revolutions cannot always be suppressed by slaughter; and that Nature, in sentencing the Circles to infecundity, has condemned them to ultimate failure --- "and herein," he says, "I see a fulfillment of the great Law of all worlds, that while the wisdom of Man thinks it is working one thing, the wisdom of Nature constrains it to work another, and quite a different and far better thing." For the rest, he begs his readers not to suppose that every minute detail in the daily life of Flatland must needs correspond to some other detail in Spaceland; and yet he hopes that, taken as a whole, his work may prove suggestive as well as amusing, to those Spacelanders of moderate and modest minds who - speaking of that which is of the highest importance, but lies beyond experience --- decline to say on the one hand, "This can never be," and on the other hand, "It must needs be precisely thus, and we know all about it."
