#lang pollen

◊(define-meta chapter-num      "3")
◊(define-meta title            "Concerning the Inhabitants of Flatland.")

◊newthought{The greatest} length or breadth of a full grown inhabitant of Flatland may be estimated at about eleven of your inches. Twelve inches may be regarded as a maximum.

Our Women are Straight Lines.

Our Soldiers and Lowest Classes of Workmen are Triangles with two equal sides, each about eleven inches long, and a base or third side so short (often not exceeding half an inch) that they form at their vertices a very sharp and formidable angle. Indeed when their bases are of the most degraded type (not more than the eighth part of an inch in size). they can hardly be distinguished from Straight Lines or Women; so extremely pointed are their vertices. With us, as with you, these Triangles are distinguished from others by being called Isosceles; and by this name I shall refer to them in the following pages.

Our Middle Class consists of Equilateral or Equal-Sided Triangles.

Our Professional Men and Gentlemen are Squares (to which class I myself belong) and Five-Sided Figures or Pentagons.

Next above these come the Nobility, of whom there are several degrees, beginning at Six-Sided Figures, or Hexagons, and from thence rising in the number of their sides till they receive the honourable title of Polygonal, or many-sided. Finally when the number of the sides becomes so numerous, and the sides themselves so small, that the figure cannot be distinguished from a circle, he is included in the Circular or Priestly order; and this is the highest class of all.

It is a Law of Nature with us that a male child shall have one more side than his, father, so that each generation shall rise (as a rule) one step in the scale of development and nobility. Thus the son of a Square is a Pentagon; the son of a Pentagon, a Hexagon; and so on.

But this rule applies not always to the Tradesmen, and still less often to the Soldiers, and to the Workmen; who indeed can hardly be said to deserve the name of human Figures, since they have not all their sides equal. With them therefore the Law of Nature does not hold; and the son of an Isosceles (i.e. a Triangle with two sides equal) remains Isosceles still. Nevertheless, all hope is not shut out, even from the Isosceles, that his posterity may ultimately rise above his degraded condition. For, after a long series of military successes, or diligent and skilful labours, it is generally found that the more intelligent among the Artisan and Soldier classes manifest a slight increase of their third side or base, and a shrinkage of the two other sides. Intermarriages (arranged by the Priests) between the sons and daughters of these more intellectual members of the lower classes generally result in an offspring approximating still more to the type of the Equal-Sided Triangle.

Rarely --- in proportion to the vast numbers of Isosceles births --- is a genuine and certifiable Equal-Sided Triangle produced from Isosceles parents.◊numbered-note{"What need of a certificate?" a Spaceland critic may ask: "Is not the procreation of a Square Son a certificate from Nature herself, proving the Equalsidedness of the Father?" I reply that no Lady of any position will marry an uncertified Triangle. Square offspring has sometimes resulted from a slightly Irregular Triangle; but in almost every such case the Irregularity of the first generation is visited on the third; which either fails to attain the Pentagonal rank, or relapses to the Triangular.} Such a birth requires, as its antecedents, not only a series of carefully arranged intermarriages, but also a long, continued exercise of frugality and self-control on the part of the would-be ancestors of the coming Equilateral, and a patient, systematic, and continuous development of the Isosceles intellect through many generations.

The birth of, a True Equilateral Triangle from Isosceles parents is the subject of rejoicing in our country for many furlongs around. After a strict examination conducted by the Sanitary and Social Board, the infant, if certified as Regular, is with solemn ceremonial admitted into the class of Equilaterals. He is then immediately taken from his proud yet sorrowing parents and adopted by some childless Equilateral, who is bound by oath never to permit the child henceforth to enter his former home or so much as to look upon his relations again, for fear lest the freshly developed organism may, by force of unconscious imitation, fall back again into his hereditary level.

The occasional emergence of an Equilateral from the ranks of his serf-born ancestors is welcomed, not only by the poor serfs themselves, as a gleam of light and hope shed upon the monotonous squalor of their existence, but also by the Aristocracy at large; for all the higher classes are well aware that these rare phenomena, while they do little or nothing to vulgarize their own privileges, serve as a most useful barrier against revolution from below.

Had the acute-angled rabble been all, without exception, absolutely destitute of hope and of ambition, they might have found leaders in some of their many seditious outbreaks, so able as to render their superior numbers and strength too much even for the wisdom of the Circles. But a wise ordinance of Nature has decreed that, in proportion as the working-classes increase in intelligence, knowledge, and all virtue, in that same proportion their acute angle (which makes them physically terrible) shall increase also and approximate to the comparatively harmless angle of the Equilateral Triangle. Thus, in the most brutal and formidable of the soldier class --- creatures almost on a level with women in their lack of intelligence --- it is found that, as they wax in the mental ability necessary to employ their tremendous penetrating power to advantage, so do they wane in the power of penetration itself.

How admirable is this Law of Compensation! And how perfect a proof of the natural fitness and, I may almost say, the divine origin of the aristocratic constitution of the States in Flatland! By a judicious use of this Law of Nature, the Polygons and Circles are almost always able to stifle sedition in its very cradle, taking advantage of the irrepressible and boundless hopefulness of the human mind. Art also comes to the aid of Law and Order. It is generally found possible --- by a little artificial compression or expansion on the part of the State physicians --- to make some of the more intelligent leaders of a rebellion perfectly Regular, and to admit them at once into the privileged classes; a much larger number, who are still below the standard, allured by the prospect of being ultimately ennobled, are induced to enter the State Hospitals, where they are kept in honourable confinement for life; one or two alone of the more obstinate, foolish, and hopelessly irregular are led to execution.

Then the wretched rabble of the Isosceles, planless and leaderless, are either transfixed without resistance by the small body of their brethren whom the Chief Circle keeps in pay for emergencies of this kind; or else more often, by means of jealousies and suspicions skilfully fomented among them by the Circular party, they are stirred to mutual warfare, and perish by one another's angles. No less than one hundred and twenty rebellions are recorded in our annals, besides minor outbreaks numbered at two hundred and thirty-five; and they have all ended thus.
