#lang pollen

◊(define-meta chapter-num      "4")
◊(define-meta title            "Concerning the Women.")

◊newthought{If our} highly pointed Triangles of the Soldier class are formidable, it may be readily inferred that far more formidable are our Women. For if a Soldier is a wedge, a Woman is a needle; being, so to speak, all point, at least at the two extremities. Add to this the power of making herself practically invisible at will, and you will perceive that a Female, in Flatland, is a creature by no means to be trifled with.

But here, perhaps, some of my younger Readers may ask how a woman in Flatland can make herself invisible. This ought, I think, to be apparent without any explanation. However, a few words will make it clear to the most unreflecting.

Place a needle on a table. Then, with your eye on the level of the table, look at it side-ways, and you see the whole length of it; but look at it end-ways, and you see nothing but a point, it has become practically invisible. Just so is it with one of our Women. When her side is turned towards us, we see her as a straight line; when the end containing her eye or mouth --- for with us these two organs are identical --- is the part that meets our eye, then we see nothing but a highly lustrous point; but when the back is presented to our view, then --- being only sub-lustrous, and, indeed, almost as dim as an inanimate object --- her hinder extremity serves her as a kind of Invisible Cap.

The dangers to which we are exposed from our Women must now be manifest to the meanest capacity in Spaceland. If even the angle of a respectable Triangle in the middle class is not without its dangers; if to run against a Working Man involves a gash; if collision with an officer of the military class necessitates a serious wound; if a mere touch from the vertex of a Private Soldier brings with it danger of death; --- what can it be to run against a Woman, except absolute and immediate destruction? And when a Woman is invisible, or visible only as a dim sub-lustrous point, how difficult must it be, even for the most cautious, always to avoid collision!

Many are the enactments made at different times in the different States of Flatland, in order to minimize this peril; and in the Southern and less temperate climates where the force of gravitation is greater, and human beings more liable to casual and involuntary motions, the Laws concerning Women are naturally much more stringent. But a general view of the Code may be obtained from the following summary: ---

◊ol{
    ◊li{Every house shall have one entrance in the Eastern side, for the use of Females only; by which all females shall enter "in a becoming and respectful manner"◊numbered-note{When I was in Spaceland I understood that some of your Priestly circles have in the same way a separate entrance for Farmers, Villagers and Teachers of Board Schools (◊i{Spectator}, Sept. 1884, p. 1255) that they may "approach in a becoming and respectful manner."} and not by the Men's or Western door.}
    ◊li{No Female shall walk in any public place without continually keeping up her Peace-cry, under penalty of death.}
    ◊li{Any Female, duly certified to be suffering from St. Vitus's Dance, fits, chronic cold accompanied by violent sneezing, or any disease necessitating involuntary motions, shall be instantly destroyed.}
}
In some of the States there is an additional Law forbidding Females, under penalty of death, from walking or standing in any public place without moving their backs constantly from right to left so as to indicate their presence to those behind them; others oblige a Woman, when travelling, to be followed by one of her sons, or servants, or by her husband; others confine Women altogether to their houses except during the religious festivals. But it has been found by the wisest of our Circles or Statesmen that the multiplication of restrictions on Females tends not only to the debilitation and diminution of the race, but also to the increase of domestic murders to such an extent that a State loses more than it gains by a too prohibitive Code.

For whenever the temper of the Women is thus exasperated by confinement at home or hampering regulations abroad, they are apt to vent their spleen upon their husbands and children; and in the less temperate climates the whole male population of a village has been sometimes destroyed in one or two hours of simultaneous female outbreak. Hence the Three Laws, mentioned above, suffice for the better regulated States, and may be accepted as a rough exemplification of our Female Code.

After all, our principal safeguard is found, not in Legislature, but in the interests of the Women themselves. For, although they can inflict instantaneous death by a retrograde movement, yet unless they can at once disengage their stinging extremity from the struggling body of their victim, their own frail bodies are liable to be shattered.

The power of Fashion is also on our side. I pointed out that in some less civilized States no female is suffered to stand in any public place without swaying her back from right to left. This practice has been universal among ladies of any pretensions to breeding in all well-governed States, as far back as the memory of Figures can reach. It is considered a disgrace to any State that legislation should have to enforce what ought to be, and is in every respectable female, a natural instinct. The rhythmical and, if I may so say, well-modulated undulation of the back in our ladies of Circular rank is envied and imitated by the wife of a common Equilateral, who can achieve nothing beyond a mere monotonous swing, like the ticking of a pendulum; and the regular tick of the Equilateral is no less admired and copied by the wife of the progressive and aspiring Isosceles, in the females of whose family no "back-motion" of any kind has become as yet a necessity of life. Hence, in every family of position and consideration, "back motion" is as prevalent as time itself; and the husbands and sons in these households enjoy immunity at least from invisible attacks.

Not that it must be for a moment supposed that our Women are destitute of affection. But unfortunately the passion of the moment predominates, in the Frail Sex, over every other consideration. This is, of course, a necessity arising from their unfortunate conformation. For as they have no pretensions to an angle, being inferior in this respect to the very lowest of the Isosceles, they are consequently wholly devoid of brain-power, and have neither reflection, judgment nor forethought, and hardly any memory. Hence, in their fits of fury, they remember no claims and recognize no distinctions. I have actually known a case where a Woman has exterminated her whole household, and half an hour afterwards, when her rage was over and the fragments swept away, has asked what has become of her husband and her children.

Obviously then a Woman is not to be irritated as long as she is in a position where she can turn round. When you have them in their apartments --- which are constructed with a view to denying them that power --- you can say and do what you like; for they are then wholly impotent for mischief, and will not remember a few minutes hence the incident for which they may be at this moment threatening you with death, nor the promises which you may have found it necessary to make in order to pacify their fury.

On the whole we get on pretty smoothly in our domestic relations, except in the lower strata of the Military Classes. There the want of tact and discretion on the part of the husbands produces at times indescribable disasters. Relying too much on the offensive weapons of their acute angles instead of the defensive organs of good sense and seasonable simulations, these reckless creatures too often neglect the prescribed construction of the women's apartments, or irritate their wives by ill-advised expressions out of doors, which they refuse immediately to retract. Moreover a blunt and stolid regard for literal truth indisposes them to make those lavish promises by which the more judicious Circle can in a moment pacify his consort. The result is massacre; not, however, without its advantages, as it eliminates the more brutal and troublesome of the Isosceles; and by many of our Circles the destructiveness of the Thinner Sex is regarded as one among many providential arrangements for suppressing redundant population, and nipping Revolution in the bud.

Yet even in our best regulated and most approximately Circular families I cannot say that the ideal of family life is so high as with you in Spaceland. There is peace, in so far as the absence of slaughter may be called by that name, but there is necessarily little harmony of tastes or pursuits; and the cautious wisdom of the Circles has ensured safety at the cost of domestic comfort. In every Circular or Polygonal household it has been a habit from time immemorial --- and now has become a kind of instinct among the women of our higher classes --- that the mothers and daughters should constantly keep their eyes and mouths towards their husband and his male friends; and for a lady in a family of distinction to turn her back upon her husband would be regarded as a kind of portent, involving loss of status. But, as I shall soon shew, this custom, though it has the advantage of safety, is not without its disadvantages.

In the house of the Working Man or respectable Tradesman --- where the wife is allowed to turn her back upon her husband, while pursuing her household avocations --- there are at least intervals of quiet, when the wife is neither seen nor heard, except for the humming sound of the continuous Peace-cry; but in the homes of the upper classes there is too often no peace. There the voluble mouth and bright penetrating eye are ever directed to wards the Master of the household; and light itself is not more persistent than the stream of feminine discourse. The tact and skill which suffice to avert a Woman's sting are unequal to the task of stopping a Woman's mouth; and as the wife has absolutely nothing to say, and absolutely no constraint of wit, sense, or conscience to prevent her from saying it, not a few cynics have been found to aver that they prefer the danger of the death-dealing but inaudible sting to the safe sonorousness of a Woman's other end.

To my readers in Spaceland the condition of our Women may seem truly deplorable, and so indeed it is. A Male of the lowest type of the Isosceles may look forward to some improvement of his angle, and to the ultimate elevation of the whole of his degraded caste; but no Woman can entertain such hopes for her sex. "Once a Woman, always a Woman" is a Decree of Nature; and the very Laws of Evolution seem suspended in her disfavour. Yet at least we can admire the wise Prearrangement which has ordained that, as they have no hopes, so they shall have no memory to recall, and no forethought to anticipate, the miseries and humiliations which are at once a necessity of their existence and the basis of the constitution of Flatland.
