#lang pollen

◊(define-meta chapter-num      "5")
◊(define-meta title            "Of our Methods of Recognizing one another.")
◊(define-meta doc-publish-date "2015-08-25")

◊newthought{You, who} are blessed with shade as well as light, you, who are gifted with two eyes, endowed with a knowledge of perspective, and charmed with the enjoyment of various colours, you, who can actually see an angle, and contemplate the complete circumference of a Circle in the happy region of the Three Dimensions --- how shall I make clear to you the extreme difficulty which we in Flatland experience in recognizing one another's configuration?

Recall what I told you above. All beings in Flatland, animate or inanimate, no matter what their form, present to our view the same, or nearly the same, appearance, viz. that of a straight Line. How then can one be distinguished from another, where all appear the same?

The answer is threefold. The first means of recognition is the sense of hearing; which with us is far more highly developed than with you, and which enables us not only to distinguish by the voice our personal friends, but even to discriminate between different classes, at least so far as concerns the three lowest orders, the Equilateral, the Square, and the Pentagon --- for of the Isosceles I take no account. But as we ascend in the social scale, the process of discriminating and being discriminated by hearing increases in difficulty, partly because voices are assimilated, partly because the faculty of voice-discrimination is a plebeian virtue not much developed among the Aristocracy. And wherever there is any danger of imposture we cannot trust to this method. Amongst our lowest orders, the vocal organs are developed to a degree more than correspondent with those of hearing, so that an Isosceles can easily feign the voice of a Polygon, and, with some training, that of a Circle himself. A second method is therefore more commonly resorted to.

◊i{Feeling} is, among our Women and lower classes --- about our upper classes I shall speak presently --- the principal test of recognition, at all events between strangers, and when the question is, not as to the individual, but as to the class. What therefore "introduction" is among the higher classes in Spaceland, that the process of "feeling" is with us. "Permit me to ask you to feel and be felt by my friend Mr. So-and-so" --- is still, among the more old- fashioned of our country gentlemen in districts remote from towns, the customary formula for a Flatland introduction. But in the towns, and among men of business, the words "be felt by" are omitted and the sentence is abbreviated to, "Let me ask you to feel Mr. So-and-so"; although it is assumed, of course, that the "feeling" is to be reciprocal. Among our still more modern and dashing young gentlemen --- who are extremely averse to superfluous effort and supremely indifferent to the purity of their native language --- the formula is still further curtailed by the use of "to feel" in a technical sense, meaning, "to recommend-for-the-purposes-of-feeling-and- being-felt"; and at this moment the "slang" of polite or fast society in the upper classes sanctions such a barbarism as "Mr. Smith, permit me to feel Mr. Jones."

Let not my Reader however suppose that "feeling" is with us the tedious process that it would be with you, or that we find it necessary to feel right round all the sides of every individual before we determine the class to which he belongs. Long practice and training, begun in the schools and continued in the experience of daily life, enable us to discriminate at once by the sense of touch, between the angles of an equal-sided Triangle, Square, and Pentagon; and I need not say that the brainless vertex of an acute angled Isosceles is obvious to the dullest touch. It is therefore not necessary, as a rule, to do more than feel a single angle of an individual; and this, once ascertained, tells us the class of the person whom we are addressing, unless indeed he belongs to the higher sections of the nobility. There the difficulty is much greater. Even a Master of Arts in our University of Wentbridge has been known to confuse a ten-sided with a twelve-sided Polygon; and there is hardly a Doctor of Science in or out of that famous University who could pretend to decide promptly and unhesitatingly between a twenty-sided and a twenty-four sided member of the Aristocracy.

Those of my readers who recall the extracts I gave above from the Legislative code concerning Women, will readily perceive that the process of introduction by contact requires some care and discretion. Otherwise the angles might inflict on the unwary Feeler irreparable injury. It is essential for the safety of the Feeler that the Felt should stand perfectly still. A start, a fidgety shifting of the position, yes, even a violent sneeze, has been known before now to prove fatal to the incautious, and to nip in the bud many a promising friendship. Especially is this true among the lower classes of the Triangles. With them, the eye is situated so far from their vertex that they can scarcely take cognizance of what goes on at that extremity of their frame. They are, moreover, of a rough coarse nature, not sensitive to the delicate touch of the highly organized Polygon. What wonder then if an involuntary toss of the head has ere now deprived the State of a valuable life!

I have heard that my excellent Grandfather --- one of the least irregular of his unhappy Isosceles class, who indeed obtained, shortly before his decease, four out of seven votes from the Sanitary and Social Board for passing him into the class of the Equal-sided --- often deplored, with a tear in his venerable eye, a miscarriage of this kind, which had occurred to his great-great-great-Grandfather, a respectable Working Man with an angle or brain of 59° 30′. According to his account, my unfortunate Ancestor, being afflicted with rheumatism, and in the act of being felt by a Polygon, by one sudden start accidentally transfixed the Great Man through the diagonal; and thereby, partly in consequence of his long imprisonment and degradation, and partly because of the moral shock which pervaded the whole of my Ancestor's relations, threw back our family a degree and a half in their ascent towards better things. The result was that in the next generation the family brain was registered at only 58°, and not till the lapse of five generations was the lost ground recovered, the full 60° attained, and the Ascent from the Isosceles finally achieved. And all this series of calamities from one little accident in the process of Feeling.

At this point I think I hear some of my better educated readers exclaim, "How could you in Flatland know anything about angles and degrees, or minutes? We can ◊em{see} an angle, because we, in the region of Space, can see two straight lines inclined to one another; but you, who can see nothing but one straight line at a time, or at all events only a number of bits of straight lines all in one straight line --- how can you ever discern any angle, and much less register angles of different sizes?"

I answer that though we cannot ◊em{see} angles, we can ◊em{infer} them, and this with great precision. Our sense of touch, stimulated by necessity, and developed by long training, enables us to distinguish angles far more accurately than your sense of sight, when unaided by a rule or measure of angles. Nor must I omit to explain that we have great natural helps. It is with us a Law of Nature that the brain of the Isosceles class shall begin at half a degree, or thirty minutes, and shall increase (if it increases at all) by half a degree in every generation; until the goal of 60° is reached, when the condition of serfdom is quitted, and the freeman enters the class of Regulars.

Consequently, Nature herself supplies us with an ascending scale or Alphabet of angles for half a degree up to 60°, Specimens of which are placed in every Elementary School throughout the land. Owing to occasional retrogressions, to still more frequent moral and intellectual stagnation, and to the extraordinary fecundity of the Criminal and Vagabond Classes, there is always a vast superfluity of individuals of the half degree and single degree class, and a fair abundance of Specimens up to 10°. These are absolutely destitute of civic rights; and a great number of them, not having even intelligence enough for the purposes of warfare, are devoted by the States to the service of education. Fettered immovably so as to remove all possibility of danger, they are placed in the class rooms of our Infant Schools, and there they are utilized by the Board of Education for the purpose of imparting to the offspring of the Middle Classes that tact and intelligence of which these wretched creatures themselves are utterly devoid.

In some States the Specimens are occasionally fed and suffered to exist for several years; but in the more temperate and better regulated regions, it is found in the long run more advantageous for the educational interests of the young, to dispense with food, and to renew the Specimens every month --- which is about the average duration of the foodless existence of the Criminal class. In the cheaper schools, what is gained by the longer existence of the Specimen is lost, partly in the expenditure for food, and partly in the diminished accuracy of the angles, which are impaired after a few weeks of constant "feeling." Nor must we forget to add, in enumerating the advantages of the more expensive system, that it tends, though slightly yet perceptibly, to the diminution of the redundant Isosceles population --- an object which every statesman in Flatland constantly keeps in view. On the whole therefore --- although I am not ignorant that, in many popularly elected School Boards, there is a reaction in favour of "the cheap system" as it is called --- I am myself disposed to think that this is one of the many cases in which expense is the truest economy.

But I must not allow questions of School Board politics to divert me from my subject. Enough has been said, I trust, to shew that Recognition by Feeling is not so tedious or indecisive a process as might have been supposed; and it is obviously more trustworthy than Recognition by hearing. Still there remains, as has been pointed out above, the objection that this method is not without danger. For this reason many in the Middle and Lower classes, and all without exception in the Polygonal and Circular orders, prefer a third method, the description of which shall be reserved for the next section.
