#lang pollen

◊(define-meta chapter-num      "7")
◊(define-meta title            "Concerning Irregular Figures.")
◊(define-meta doc-publish-date "25/08/2015")

◊newthought{Throughout the} previous pages I have been assuming --- what perhaps should have been laid down at the beginning as a distinct and fundamental proposition --- that every human being in Flatland is a Regular Figure, that is to say of regular construction. By this I mean that a Woman must not only be a line, but a straight line; that an Artisan or Soldier must have two of his sides equal; that Tradesmen must have three sides equal; Lawyers (of which class I am a humble member), four sides equal, and, generally, that in every Polygon, all the sides must be equal.

The size of the sides would of course depend upon the age of the individual. A Female at birth would be about an inch long, while a tall adult Woman might extend to a foot. As to the Males of every class, it may be roughly said that the length of an adult's sides, when added together, is two feet or a little more. But the size of our sides is not under consideration. I am speaking of the ◊em{equality} of sides, and it does not need much reflection to see that the whole of the social life in Flatland rests upon the fundamental fact that Nature wills all Figures to have their sides equal.

If our sides were unequal our angles might be unequal. Instead of its being sufficient to feel, or estimate by sight, a single angle in order to determine the form of an individual, it would be necessary to ascertain each angle by the experiment of Feeling. But life would be too short for such a tedious grouping. The whole science and art of Sight Recognition would at once perish; Feeling, so far as it is an art, would not long survive; intercourse would become perilous or impossible; there would be an end to all confidence, all forethought; no one would be safe in making the most simple social arrangements; in a word, civilization would relapse into barbarism.

Am I going too fast to carry my Readers with me to these obvious conclusions? Surely a moment's reflection, and a single instance from common life, must convince every one that our whole social system is based upon Regularity, or Equality of Angles. You meet, for example, two or three Tradesmen in the street, whom you recognize at once to be Tradesmen by a glance at their angles and rapidly bedimmed sides, and you ask them to step into your house to lunch. This you do at present with perfect confidence, because everyone knows to an inch or two the area occupied by an adult Triangle: but imagine that your Tradesman drags behind his regular and respectable vertex, a parallelogram of twelve or thirteen inches in diagonal: --- what are you to do with such a monster sticking fast in your house door?

But I am insulting the intelligence of my Readers by accumulating details which must be patent to everyone who enjoys the advantages of a Residence in Spaceland. Obviously the measurements of a single angle would no longer be sufficient under such portentous circumstances; one's whole life would be taken up in feeling or surveying the perimeter of one's acquaintances. Already the difficulties of avoiding a collision in a crowd are enough to tax the sagacity of even a well-educated Square; but if no one could calculate the Regularity of a single figure in the company, all would be chaos and confusion, and the slightest panic would cause serious injuries, or --- if there happened to be any Women or Soldiers present --- perhaps considerable loss of life.

Expediency therefore concurs with Nature in stamping the seal of its approval upon Regularity of conformation: nor has the Law been backward in seconding their efforts. "Irregularity of Figure" means with us the same as, or more than, a combination of moral obliquity and criminality with you, and is treated accordingly. There are not wanting, it is true, some promulgators of paradoxes who maintain that there is no necessary connection between geometrical and moral Irregularity. "The Irregular," they say, "is from his birth scouted by his own parents, derided by his brothers and sisters, neglected by the domestics, scorned and suspected by society, and excluded from all posts of responsibility, trust, and useful activity. His every movement is jealously watched by the police till he comes of age and presents himself for inspection; then he is either destroyed, if he is found to exceed the fixed margin of deviation, or else immured in a Government Office as a clerk of the seventh class; prevented from marriage; forced to drudge at an uninteresting occupation for a miserable stipend; obliged to live and board at the office, and to take even his vacation under close supervision; what wonder that human nature, even in the best and purest, is embittered and perverted by such surroundings!"

All this very plausible reasoning does not convince me, as it has not convinced the wisest of our Statesmen, that our ancestors erred in laying it down as an axiom of policy that the toleration of Irregularity is incompatible with the safety of the State. Doubtless, the life of an Irregular is hard; but the interests of the Greater Number require that it shall be hard. If a man with a triangular front and a polygonal back were allowed to exist and to propagate a still more Irregular posterity, what would become of the arts of life? Are the houses and doors and churches in Flatland to be altered in order to accommodate such monsters? Are our ticket collectors to be required to measure every man's perimeter before they allow him to enter a theatre, or to take his place in a lecture room? Is an Irregular to be exempted from the militia? And if not, how is he to be prevented from carrying desolation into the ranks of his comrades? Again, what irresistible temptations to fraudulent impostures must needs beset such a creature! How easy for him to enter a shop with his polygonal front foremost, and to order goods to any extent from a confiding tradesman! Let the advocates of a falsely called Philanthropy plead as they may for the abrogation of the Irregular Penal Laws, I for my part have never known an Irregular who was not also what Nature evidently intended him to be --- a hypocrite, a misanthropist, and, up to the limits of his power, a perpetrator of all manner of mischief.

Not that I should be disposed to recommend (at present) the extreme measures adopted in some States, where an infant whose angle deviates by half a degree from the correct angularity is summarily destroyed at birth. Some of our highest and ablest men, men of real genius, have during their earliest days laboured under deviations as great as, or even greater than, forty-five minutes: and the loss of their precious lives would have been an irreparable injury to the State. The art of healing also has achieved some of its most glorious triumphs in the compressions, extensions, trepannings, colligations, and other surgical or diaetetic operations by which Irregularity has been partly or wholly cured. Advocating therefore a ◊i{Via Media}, I would lay down no fixed or absolute line of demarcation; but at the period when the frame is just beginning to set, and when the Medical Board has reported that recovery is improbable, I would suggest that the Irregular offspring be painlessly and mercifully consumed.
