#lang pollen

◊(define-meta chapter-num      "8")
◊(define-meta title            "Of the Ancient Practice of Painting.")
◊(define-meta doc-publish-date "25/08/2015")

◊newthought{If my} Readers have followed me with any attention up to this point, they will not be surprised to hear that life is somewhat dull in Flatland. I do not, of course, mean that there are not battles, conspiracies, tumults, factions, and all those other phenomena which are supposed to make History interesting; nor would I deny that the strange mixture of the problems of life and the problems of Mathematics, continually inducing conjecture and giving the opportunity of immediate verification, imparts to our existence a zest which you in Spaceland can hardly comprehend. I speak now from the aesthetic and artistic point of view when I say that life with us is dull; aesthetically and artistically, very dull indeed.

How can it be otherwise, when all one's prospect, all one's landscapes, historical pieces, portraits, flowers, still life, are nothing but a single line, with no varieties except degrees of brightness and obscurity?

It was not always thus. Colour, if Tradition speaks the truth, once for the space of half a dozen centuries or more, threw a transient splendour over the lives of our ancestors in the remotest ages. Some private individual --- a Pentagon whose name is variously reported --- having casually discovered the constituents of the simpler colours and a rudimentary method of painting, is said to have begun decorating first his house, then his slaves, then his Father, his Sons, and Grandsons, lastly himself. The convenience as well as the beauty of the results commended themselves to all. Wherever Chromatistes, --- for by that name the most trustworthy authorities concur in calling him, --- turned his variegated frame, there he at once excited attention, and attracted respect. No one now needed to "feel" him; no one mistook his front for his back; all his movements were readily ascertained by his neighbours without the slightest strain on their powers of calculation; no one jostled him, or failed to make way for him; his voice was saved the labour of that exhausting utterance by which we colourless Squares and Pentagons are often forced to proclaim our individuality when we move amid a crowd of ignorant Isosceles.

The fashion spread like wildfire. Before a week was over, every Square and Triangle in the district had copied the example of Chromatistes, and only a few of the more conservative Pentagons still held out. A month or two found even the Dodecagons infected with the innovation. A year had not elapsed before the habit had spread to all but the very highest of the Nobility. Needless to say, the custom soon made its way from the district of Chromatistes to surrounding regions; and within two generations no one in all Flatland was colourless except the Women and the Priests.

Here Nature herself appeared to erect a barrier, and to plead against extending the innovation to these two classes. Many- sidedness was almost essential as a pretext for the Innovators. "Distinction of sides is intended by Nature to imply distinction of colours" --- such was the sophism which in those days flew from mouth to mouth, converting whole towns at a time to the new culture. But manifestly to our Priests and Women this adage did not apply. The latter had only one side, and therefore --- plurally and pedantically speaking --- ◊em{no sides}. The former --- if at least they would assert their claim to be really and truly Circles, and not mere high-class Polygons with an infinitely large number of infinitesimally small sides --- were in the habit of boasting (what Women confessed and deplored) that they also had no sides, being blessed with a perimeter of one line, or, in other words, a Circumference. Hence it came to pass that these two Classes could see no force in the so-called axiom about "Distinction of Sides implying Distinction of Colour;" and when all others had succumbed to the fascinations of corporal decoration, the Priests and the Women alone still remained pure from the pollution of paint.

Immoral, licentious, anarchical, unscientific --- call them by what names you will --- yet, from an aesthetic point of view, those ancient days of the Colour Revolt were the glorious childhood of Art in Flatland --- a childhood, alas, that never ripened into manhood, nor even reached the blossom of youth. To live was then in itself a delight, because living implied seeing. Even at a small party, the company was a pleasure to behold; the richly varied hues of the assembly in a church or theatre are said to have more than once proved too distracting for our greatest teachers and actors; but most ravishing of all is said to have been the unspeakable magnificence of a military review.

The sight of a line of battle of twenty thousand Isosceles suddenly facing about, and exchanging the sombre black of their bases for the orange and purple of the two sides including their acute angle; the militia of the Equilateral Triangles tricoloured in red, white, and blue; the mauve, ultra-marine, gamboge, and burnt umber of the Square artillerymen rapidly rotating near their vermilion guns; the dashing and flashing of the five-coloured and six-coloured Pentagons and Hexagons careering across the field in their offices of surgeons, geometricians and aides-de-camp --- all these may well have been sufficient to render credible the famous story how an illustrious Circle, overcome by the artistic beauty of the forces under his command, threw aside his marshal's baton and his royal crown, exclaiming that he henceforth exchanged them for the artist's pencil. How great and glorious the sensuous development of these days must have been is in part indicated by the very language and vocabulary of the period. The commonest utterances of the commonest citizens in the time of the Colour Revolt seem to have been suffused with a richer tinge of word or thought; and to that era we are even now indebted for our finest poetry and for whatever rhythm still remains in the more scientific utterance of these modern days.
