#lang pollen

◊(define-meta chapter-num      "9")
◊(define-meta title            "Of the Universal Colour Bill.")

◊newthought{But meanwhile} the intellectual Arts were fast decaying.

The Art of Sight Recognition, being no longer needed, was no longer practised; and the studies of Geometry, Statics, Kinetics, and other kindred subjects, came soon to be considered superfluous, and fell into disrespect and neglect even at our University. The inferior Art of Feeling speedily experienced the same fate at our Elementary Schools. Then the Isosceles classes, asserting that the Specimens were no longer used nor needed, and refusing to pay the customary tribute from the Criminal classes to the service of Education, waxed daily more numerous and more insolent on the strength of their immunity from the old burden which had formerly exercised the twofold wholesome effect of at once taming their brutal nature and thinning their excessive numbers.

Year by year the Soldiers and Artisans began more vehemently to assert --- and with increasing truth --- that there was no great difference between them and the very highest class of Polygons, now that they were raised to an equality with the latter, and enabled to grapple with all the difficulties and solve all the problems of life, whether Statical or Kinetical, by the simple process of Colour Recognition. Not content with the natural neglect into which Sight Recognition was falling, they began boldly to demand the legal prohibition of all "monopolizing and aristocratic Arts" and the consequent abolition of all endowments for the studies of Sight Recognition, Mathematics, and Feeling. Soon, they began to insist that inasmuch as Colour, which was a second Nature, had destroyed the need of aristocratic distinctions, the Law should follow in the same path, and that henceforth all individuals and all classes should be recognized as absolutely equal and entitled to equal rights.

Finding the higher Orders wavering and undecided, the leaders of the Revolution advanced still further in their requirements, and at last demanded that all classes alike, the Priests and the Women not excepted, should do homage to Colour by submitting to be painted. When it was objected that Priests and Women had no sides, they retorted that Nature and Expediency concurred in dictating that the front half of every human being (that is to say, the half containing his eye and mouth) should be distinguishable from his hinder half. They therefore brought before a general and extraordinary Assembly of all the States of Flatland a Bill proposing that in every Woman the half containing the eye and mouth should be coloured red, and the other half green. The Priests were to be painted in the same way, red being applied to that semicircle in which the eye and mouth formed the middle point; while the other or hinder semicircle was to be coloured green.

There was no little cunning in this proposal, which indeed emanated not from any Isosceles --- for no being so degraded would have had angularity enough to appreciate, much less to devise, such a model of state-craft --- but from an Irregular Circle who, instead of being destroyed in his childhood, was reserved by a foolish indulgence to bring desolation on his country and destruction on myriads of his followers.

On the one hand the proposition was calculated to bring the Women in all classes over to the side of the Chromatic Innovation. For by assigning to the Women the same two colours as were assigned to the Priests, the Revolutionists thereby ensured that, in certain positions, every Woman would appear like a Priest, and be treated with corresponding respect and deference --- a prospect that could not fail to attract the female Sex in a mass.

But by some of my Readers the possibility of the identical appearance of Priests and Women, under the new Legislation, may not be recognized; if so, a word or two will make it obvious.

Imagine a woman duly decorated, according to the new Code; with the front half (◊i{i.e.} the half containing eye and mouth) red, and with the hinder half green. Look at her from one side. Obviously you will see a straight line, ◊emph{half red, half green}.

◊margin-figure["img/ch09-fig01.png"]{A Priest as seen from his side}

Now imagine a Priest, whose mouth is at ◊∆{M}, and whose front semicircle ◊∆{(AMB)} is consequently coloured red, while his hinder semicircle is green; so that the diameter AB divides the green from the red. If you contemplate the Great Man so as to have your eye in the same straight line as his dividing diameter ◊∆{(AB)}, what you will see will be a straight line ◊∆{(CBD)}, of which ◊emph{one half} ◊∆{(CB)} ◊emph{will be red, and the other} ◊∆{(BD)} ◊emph{green}. The whole line ◊∆{(CD)} will be rather shorter perhaps than that of a full-sized Woman, and will shade off more rapidly towards its extremities; but the identity of the colours would give you an immediate impression of identity of Class, making you neglectful of other details. Bear in mind the decay of Sight Recognition which threatened society at the time of the Colour Revolt; add too the certainty that Women would speedily learn to shade off their extremities so as to imitate the Circles; it must then be surely obvious to you, my dear Reader, that the Colour Bill placed us under a great danger of confounding a Priest with a young Woman.

How attractive this prospect must have been to the Frail Sex may readily be imagined. They anticipated with delight the confusion that would ensue. At home they might hear political and ecclesiastical secrets intended not for them but for their husbands and brothers, and might even issue commands in the name of a priestly Circle; out of doors the striking combination of red and green, without addition of any other colours, would be sure to lead the common people into endless mistakes, and the Women would gain whatever the Circles lost, in the deference of the passers by. As for the scandal that would befall the Circular Class if the frivolous and unseemly conduct of the Women were imputed to them, and as to the consequent subversion of the Constitution, the Female Sex could not be expected to give a thought to these considerations. Even in the households of the Circles, the Women were all in favour of the Universal Colour Bill.

The second object aimed at by the Bill was the gradual demoralization of the Circles themselves. In the general intellectual decay they still preserved their pristine clearness and strength of understanding. From their earliest childhood, familiarized in their Circular households with the total absence of Colour, the Nobles alone preserved the Sacred Art of Sight Recognition, with all the advantages that result from that admirable training of the intellect. Hence, up to the date of the introduction of the Universal Colour Bill, the Circles had not only held their own, but even increased their lead of the other classes by abstinence from the popular fashion.

Now therefore the artful Irregular whom I described above as the real author of this diabolical Bill, determined at one blow to lower the status of the Hierarchy by forcing them to submit to the pollution of Colour, and at the same time to destroy their domestic opportunities of training in the Art of Sight Recognition, so as to enfeeble their intellects by depriving them of their pure and colourless homes. Once subjected to the chromatic taint, every parental and every childish Circle would demoralize each other. Only in discerning between the Father and the Mother would the Circular infant find problems for the exercise of its understanding --- problems too often likely to be corrupted by maternal impostures with the result of shaking the child's faith in all logical conclusions. Thus by degrees the intellectual lustre of the Priestly Order would wane, and the road would then lie open for a total destruction of all Aristocratic Legislature and for the subversion of our Privileged Classes.
