#lang pollen

◊(define-meta chapter-num      "10")
◊(define-meta title            "Of the Suppression of the Chromatic Sedition.")

◊newthought{The agitation} for the Universal Colour Bill continued for three years; and up to the last moment of that period it seemed as though Anarchy were destined to triumph.

A whole army of Polygons, who turned out to fight as private soldiers, was utterly annihilated by a superior force of Isosceles Triangles --- the Squares and Pentagons meanwhile remaining neutral. Worse than all, some of the ablest Circles fell a prey to conjugal fury. Infuriated by political animosity, the wives in many a noble household wearied their lords with prayers to give up their opposition to the Colour Bill; and some, finding their entreaties fruitless, fell on and slaughtered their innocent children and husband, perishing themselves in the act of carnage. It is recorded that during that triennial agitation no less than twenty three Circles perished in domestic discord.

Great indeed was the peril. It seemed as though the Priests had no choice between submission and extermination; when suddenly the course of events was completely changed by one of those picturesque incidents which Statesmen ought never to neglect, often to anticipate, and sometimes perhaps to originate, because of the absurdly disproportionate power with which they appeal to the sympathies of the populace.

It happened that an Isosceles of a low type, with a brain little if at all above four degrees --- accidentally dabbling in the colours of some Tradesman whose shop he had plundered --- painted himself, or caused himself to be painted (for the story varies) with the twelve colours of a Dodecagon. Going into the Market Place he accosted in a feigned voice a maiden, the orphan daughter of a noble Polygon, whose affection in former days he had sought in vain; and by a series of deceptions --- aided, on the one side, by a string of lucky accidents too long to relate, and on the other, by an almost inconceivable fatuity and neglect of ordinary precautions on the part of the relations of the bride --- he succeeded in consummating the marriage. The unhappy girl committed suicide on discovering the fraud to which she had been subjected.

When the news of this catastrophe spread from State to State the minds of the Women were violently agitated. Sympathy with the miserable victim and anticipations of similar deceptions for themselves, their sisters, and their daughters, made them now regard the Colour Bill in an entirely new aspect. Not a few openly avowed themselves converted to antagonism; the rest needed only a slight stimulus to make a similar avowal. Seizing this favourable opportunity, the Circles hastily convened an extraordinary Assembly of the States; and besides the usual guard of Convicts, they secured the attendance of a large number of reactionary Women.

Amidst an unprecedented concourse, the Chief Circle of those days --- by name Pantocyclus --- arose to find himself hissed and hooted by a hundred and twenty thousand Isosceles. But he secured silence by declaring that henceforth the Circles would enter on a policy of Concession; yielding to the wishes of the majority, they would accept the Colour Bill. The uproar being at once converted to applause, he invited Chromatistes, the leader of the Sedition, into the centre of the hall, to receive in the name of his followers the submission of the Hierarchy. Then followed a speech, a masterpiece of rhetoric, which occupied nearly a day in the delivery, and to which no summary can do justice.

With a grave appearance of impartiality he declared that as they were now finally committing themselves to Reform or Innovation, it was desirable that they should take one last view of the perimeter of the whole subject, its defects as well as its advantages. Gradually introducing the mention of the dangers to the Tradesmen, the Professional Classes and the Gentlemen, he silenced the rising murmurs of the Isosceles by reminding them that, in spite of all these defects, he was willing to accept the Bill if it was approved by the majority. But it was manifest that all, except the Isosceles, were moved by his words and were either neutral or averse to the Bill.

Turning now to the Workmen he asserted that their interests must not be neglected, and that, if they intended to accept the Colour Bill, they ought at least to do so with full view of the consequences. Many of them, he said, were on the point of being admitted to the class of the Regular Triangles; others anticipated for their children a distinction they could not hope for themselves. That honourable ambition would now have to be sacrificed. With the universal adoption of Colour, all distinctions would cease; Regularity would be confused with Irregularity; development would give place to retrogression; the Workman would in a few generations be degraded to the level of the Military, or even the Convict Class; political power would be in the hands of the greatest number, that is to say the Criminal Classes, who were already more numerous than the Workmen, and would soon out-number all the other Classes put together when the usual Compensative Laws of Nature were violated.

A subdued murmur of assent ran through the ranks of the Artisans, and Chromatistes, in alarm, attempted to step forward and address them. But he found himself encompassed with guards and forced to remain silent while the Chief Circle in a few impassioned words made a final appeal to the Women, exclaiming that, if the Colour Bill passed, no marriage would henceforth be safe, no woman's honour secure; fraud, deception, hypocrisy would pervade every household; domestic bliss would share the fate of the Constitution and pass to speedy perdition. "Sooner than this," he cried, "Come death."

At these words, which were the preconcerted signal for action, the Isosceles Convicts fell on and transfixed the wretched Chromatistes; the Regular Classes, opening their ranks, made way for a band of Women who, under direction of the Circles, moved, back foremost, invisibly and unerringly upon the unconscious soldiers; the Artisans, imitating the example of their betters, also opened their ranks. Meantime bands of Convicts occupied every entrance with an impenetrable phalanx.

The battle, or rather carnage, was of short duration. Under the skillful generalship of the Circles almost every Woman's charge was fatal and very many extracted their sting uninjured, ready for a second slaughter. But no second blow was needed; the rabble of the Isosceles did the rest of the business for themselves. Surprised, leaderless, attacked in front by invisible foes, and finding egress cut off by the Convicts behind them, they at once --- after their manner --- lost all presence of mind, and raised the cry of "treachery." This sealed their fate. Every Isosceles now saw and felt a foe in every other. In half an hour not one of that vast multitude was living; and the fragments of seven score thousand of the Criminal Class slain by one another's angles attested the triumph of Order.

The Circles delayed not to push their victory to the uttermost. The Working Men they spared but decimated. The Militia of the Equilaterals was at once called out; and every Triangle suspected of Irregularity on reasonable grounds, was destroyed by Court Martial, without the formality of exact measurement by the Social Board. The homes of the Military and Artisan classes were inspected in a course of visitations extending through upwards of a year; and during that period every town, village, and hamlet was systematically purged of that excess of the lower orders which had been brought about by the neglect to pay the tribute of Criminals to the Schools and University, and by the violation of the other natural Laws of the Constitution of Flatland. Thus the balance of classes was again restored.

Needless to say that henceforth the use of Colour was abolished, and its possession prohibited. Even the utterance of any word denoting Colour, except by the Circles or by qualified scientific teachers, was punished by a severe penalty. Only at our University in some of the very highest and most esoteric classes --- which I myself have never been privileged to attend --- it is understood that the sparing use of Colour is still sanctioned for the purpose of illustrating some of the deeper problems of mathematics. But of this I can only speak from hearsay.

Elsewhere in Flatland, Colour is now non-existent. The art of making it is known to only one living person, the Chief Circle for the time being; and by him it is handed down on his deathbed to none but his Successor. One manufactory alone produces it; and, lest the secret should be betrayed, the Workmen are annually consumed, and fresh ones introduced. So great is the terror with which even now our Aristocracy looks back to the far distant days of the agitation for the Universal Colour Bill.
