#lang pollen

◊(define-meta chapter-num      "11")
◊(define-meta title            "Concerning Our Priests.")

◊newthought{It is} high time that I should pass from these brief and discursive notes about things in Flatland to the central event of this book, my initiation into the mysteries of Space. ◊emph{That} is my subject; all that has gone before is merely preface.

For this reason I must omit many matters of which the explanation would not, I flatter myself, be without interest for my Readers: as for example, our method of propelling and stopping ourselves, although destitute of feet; the means by which we give fixity to structures of wood, stone, or brick, although of course we have no hands, nor can we lay foundations as you can, nor avail ourselves of the lateral pressure of the earth; the manner in which the rain originates in the intervals between our various zones, so that the northern regions do not intercept the moisture from falling on the southern; the nature of our hills and mines, our trees and vegetables, our seasons and harvests; our Alphabet and method of writing, adapted to our linear tablets; these and a hundred other details of our physical existence I must pass over, nor do I mention them now except to indicate to my readers that their omission proceeds not from forgetfulness on the part of the author, but from his regard for the time of the Reader.

Yet before I proceed to my legitimate subject some few final remarks will no doubt be expected by my Readers upon those pillars and mainstays of the Constitution of Flatland, the controllers of our conduct and shapers of our destiny, the objects of universal homage and almost of adoration: need I say that I mean our Circles or Priests?

When I call them Priests, let me not be understood as meaning no more than the term denotes with you. With us, our Priests are Administrators of all Business, Art, and Science; Directors of Trade, Commerce, Generalship, Architecture, Engineering, Education, Statesmanship, Legislature, Morality, Theology; doing nothing themselves, they are the Causes of everything worth doing, that is done by others.

Although popularly everyone called a Circle is deemed a Circle, yet among the better educated Classes it is known that no Circle is really a Circle, but only a Polygon with a very large number of very small sides. As the number of the sides increases, a polygon approximates to a Circle; and, when the number is very great indeed, say for example three or four hundred, it is extremely difficult for the most delicate touch to feel any polygonal angles. Let me say rather, it ◊emph{would} be difficult: for, as I have shown above, Recognition by Feeling is unknown among the highest society, and to ◊emph{feel} a Circle would be considered a most audacious insult. This habit of abstention from Feeling in the best society enables a Circle the more easily to sustain the veil of mystery in which, from his earliest years, he is wont to enwrap the exact nature of his Perimeter or Circumference. Three feet being the average Perimeter it follows that, in a polygon of three hundred sides each side will be no more than the hundredth part of a foot in length, or little more than the tenth part of an inch; and in a Polygon of six or seven hundred sides the sides are little larger than the diameter of a spaceland pin-head. It is always assumed, by courtesy, that the Chief Circle for the time being has ten thousand sides.

The ascent of the posterity of the Circles in the social scale is not restricted, as it is among the lower Regular classes, by the Law of Nature which limits the increase of sides to one in each generation. If it were so, the number of sides in a Circle would be a mere question of pedigree and arithmetic, and the four hundred and ninety-seventh descendant of an Equilateral Triangle would necessarily be a Polygon with five hundred sides. But this is not the case. Nature’s Law prescribes two antagonistic decrees affecting Circular propagation; first, that as the race climbs higher in the scale of development, so development shall proceed at an accelerated pace; second, that in the same proportion, the race shall become less fertile. Consequently in the home of a Polygon of four or five hundred sides it is rare to find a son; more than one is never seen. On the other hand the son of a five-hundred sided Polygon has been known to possess five hundred and fifty, or even six hundred sides.

Art also steps in to help the process of the higher Evolution. Our physicians have discovered that the small and tender sides of an infant Polygon of the higher class can be fractured, and his whole frame re-set, with such exactness that a Polygon of two or three hundred sides sometimes --- by no means always, for the process is attended with serious risk --- but sometimes overleaps two or three hundred generations, and as if were doubles at a stroke, the number of his progenitors and the nobility of his descent.

Many a promising child is sacrificed in this way. Scarcely one out of ten survives. Yet so strong is the parental ambition among those Polygons who are, as it were, on the fringe of the Circular class, that it is very rare to find a Nobleman of that position in society, who has neglected to place his first-born in the Circular Neo-Therapeutic Gymnasium before he has attained the age of a month.

One year determines success or failure. At the end of that time the child has, in all probability, added one more to the tombstones that crowd the Neo-Therapeutic Cemetery; but on rare occasions a glad procession bears back the little one to his exultant parents, no longer a Polygon, but a Circle, at least by courtesy: and a single instance of so blessed a result induces multitudes of Polygonal parents to submit to similar domestic sacrifices, which have a dissimilar issue.
