#lang pollen

◊(define-meta chapter-num      "12")
◊(define-meta title            "Of the Doctrine of our Priests.")

◊newthought{As to} the doctrine of the Circles it may briefly be summed up in a single maxim, "Attend to your Configuration." Whether political, ecclesiastical, or moral, all their teaching has for its object the improvement of individual and collective Configuration --- with special reference of course to the Configuration of the Circles, to which all other objects are subordinated.

It is the merit of the Circles that they have effectually Suppressed those ancient heresies which led men to waste energy and sympathy in the vain belief that conduct depends upon will, effort, training, encouragement, praise, or anything else but Configuration. It was Pantocyclus --- the illustrious Circle mentioned above, as the queller of the Colour Revolt --- who first convinced mankind that Configuration makes the man; that if, for example, you are born an Isosceles with two uneven sides, you will assuredly go wrong unless you have them made even --- for which purpose you must go to the Isosceles Hospital; similarly, if you are a Triangle, or Square, or even a Polygon, born with any Irregularity, you must be taken to one of the Regular Hospitals to have your disease cured; otherwise you will end your days in the State Prison or by the angle of the State Executioner.

All faults or defects, from the slightest misconduct to the most flagitious crime, Pantocyclus attributed to some deviation from perfect Regularity in the bodily figure, caused perhaps (if not congenital) by some collision in a crowd; by neglect to take exercise, or by taking too much of it; or even by a sudden change of temperature, resulting in a shrinkage or expansion in some too susceptible part of the frame. Therefore, concluded that illustrious Philosopher, neither good conduct nor bad conduct is a fit subject, in any sober estimation, for either praise or blame. For why should you praise, for example, the integrity of a Square who faithfully defends the interests of his client, when you ought in reality rather to admire the exact precision of his right angles? Or again, why blame a lying, thievish Isosceles when you ought rather to deplore the incurable inequality of his sides?

Theoretically, this doctrine is unquestionable; but it has practical drawbacks. In dealing with an Isosceles, if a rascal pleads that he cannot help stealing because of his unevenness, you reply that for that very reason, because he cannot help being a nuisance to his neighbours, you, the Magistrate, cannot help sentencing him to be consumed --- and there's an end of the matter. But in little domestic difficulties, where the penalty of consumption, or death, is out of the question, this theory of Configuration sometimes comes in awkwardly; and I must confess that occasionally when one of my own Hexagonal Grandsons pleads as an excuse for his disobedience that a sudden change of the temperature has been too much for his perimeter, and that I ought to lay the blame not on him but on his Configuration, which can only be strengthened by abundance of the choicest sweetmeats, I neither see my way logically to reject, nor practically to accept, his conclusions.

For my own part, I find it best to assume that a good sound scolding or castigation has some latent and strengthening influence on my Grandson's Configuration; though I own that I have no grounds for thinking so. At all events I am not alone in my way of extricating myself from this dilemma; for I find that many of the highest Circles, sitting as Judges in law courts, use praise and blame towards Regular and Irregular Figures; and in their homes I know by experience that, when scolding their children, they speak about "right" or "wrong" as vehemently and passionately as if they believed that these names represented real existences, and that a human Figure is really capable of choosing between them.

Constantly carrying out their policy of making Configuration the leading idea in every mind, the Circles reverse the nature of that Commandment which in Spaceland regulates the relations between parents and children. With you, children are taught to honour their parents; with us --- next to the Circles, who are the chief object of universal homage --- a man is taught to honour his Grandson, if he has one; or, if not, his Son. By "honour," however, is by no means meant "indulgence," but a reverent regard for their highest interests: and the Circles teach that the duty of fathers is to subordinate their own interests to those of posterity, thereby advancing the welfare of the whole State as well as that of their own immediate descendants.

The weak point in the system of the Circles --- if a humble Square may venture to speak of anything Circular as containing any element of weakness --- appears to me to be found in their relations with Women.

As it is of the utmost importance for Society that Irregular births should be discouraged, it follows that no Woman who has any Irregularities in her ancestry is a fit partner for one who desires that his posterity should rise by regular degrees in the social scale.

Now the Irregularity of a Male is a matter of measurement; but as all Women are straight, and therefore visibly Regular so to speak, one has to devise some other means of ascertaining what I may call their invisible Irregularity, that is to say their potential Irregularities as regards possible offspring. This is effected by carefully-kept pedigrees, which are preserved and supervised by the State; and without a certified pedigree no Woman is allowed to marry.

Now it might have been supposed that a Circle --- proud of his ancestry and regardful for a posterity which might possibly issue hereafter in a Chief Circle --- would be more careful than any other to choose a wife who had no blot on her escutcheon. But it is not so. The care in choosing a Regular wife appears to diminish as one rises in the social scale. Nothing would induce an aspiring Isosceles, who had hopes of generating an Equilateral Son, to take a wife who reckoned a single Irregularity among her Ancestors; a Square or Pentagon, who is confident that his family is steadily on the rise, does not inquire above the five-hundredth generation; a Hexagon or Dodecagon is even more careless of the wife's pedigree; but a Circle has been known deliberately to take a wife who has had an Irregular Great- Grandfather, and all because of some slight superiority of lustre, or because of the charms of a low voice --- which, with us, even more than you, is thought "an excellent thing in Woman."

Such ill-judged marriages are, as might be expected, barren, if they do not result in positive Irregularity or in diminution of sides; but none of these evils have hitherto proved sufficiently deterrent. The loss of a few sides in a highly-developed Polygon is not easily noticed, and is sometimes compensated by a successful operation in the Neo-Therapeutic Gymnasium, as I have described above; and the Circles are too much disposed to acquiesce in infecundity as a Law of the superior development. Yet, if this evil be not arrested, the gradual diminution of the Circular class may soon become more rapid, and the time may be not far distant when, the race being no longer able to produce a Chief Circle, the Constitution of Flatland must fall.

One other word of warning suggests itself to me, though I cannot so easily mention a remedy; and this also refers to our relations with Women. About three hundred years ago, it was decreed by the Chief Circle that, since women are deficient in Reason but abundant in Emotion, they ought no longer to be treated as rational, nor receive any mental education. The consequence was that they were no longer. taught to read, nor even to master Arithmetic enough to enable them to count the angles of their husband or children; and hence they sensibly declined during each generation in intellectual power. And this system of female non-education or quietism still prevails.

My fear is that, with the best intentions, this policy has been carried so far as to react injuriously on the Male Sex.

For the consequence is that, as things now are, we Males have to lead a kind of bi-lingual, and I may almost say bi-mental, existence. With Women, we speak of "love," "duty," "right," "wrong," "pity," "hope," and other irrational and emotional conceptions, which have no existence, and the fiction of which has no object except to control feminine exuberances; but among ourselves, and in our books, we have an entirely different vocabulary and I may almost say, idiom. "Love" then becomes "the anticipation of benefits"; "duty" becomes "necessity" or "fitness"; and other words are correspondingly transmuted. Moreover, among Women, we use language implying the utmost deference for their Sex; and they fully believe that the Chief Circle Himself is not more devoutly adored by us than they are: but behind their backs they are both regarded and spoken of --- by all except the very young --- as being little better than "mindless organisms."

Our Theology also in the Women's chambers is entirely different from our Theology elsewhere.

Now my humble fear is that this double training, in language as well as in thought, imposes somewhat too heavy a burden upon the young, especially when, at the age of three years old, they are taken from the maternal care and taught to unlearn the old language --- except for the purpose of repeating it in the presence of their Mothers and Nurses-and to learn the vocabulary and idiom of science. Already methinks I discern a weakness in the grasp of mathematical truth at the present time as compared with the more robust intellect of our ancestors three hundred years ago. I say nothing of the possible danger if a Woman should ever surreptitiously learn to read and convey to her Sex the result of her perusal of a single popular volume; nor of the possibility that the indiscretion or disobedience of some infant Male might reveal to a Mother the secrets of the logical dialect. On the simple ground of the enfeebling of the Male intellect, I rest this humble appeal to the highest Authorities to reconsider the regulations of Female education.
