#lang pollen

◊(define-meta chapter-num      "15")
◊(define-meta title            "Concerning a Stranger from Spaceland.")

◊newthought{From dreams} I proceed to facts.

It was the last day of the 1999th year of our era. The pattering of the rain had long ago announced nightfall; and I was sitting◊numbered-note{When I say "sitting," of course I do not mean any change of attitude such as you in Spaceland signify by that word: for as we have no feet, we can no more "sit" nor "stand" (in your sense of the word) than one of your soles or flounders. Nevertheless, we perfectly well recognize the different mental states of volition implied in "lying," "sitting," and "standing," which are to some extent indicated to a beholder by a slight increase of lustre corresponding to the increase of volition. But on this, and a thousand other kindred subjects, time forbids me to dwell.} in the company of my wife, musing on the events of the past and the prospects of the coming year, the coming century, the coming Millennium.

My four Sons and two orphan Grandchildren had retired to their several apartments; and my wife alone remained with me to see the old Millennium out and the new one in. I was rapt in thought, pondering in my mind some words that had casually issued from the mouth of my youngest Grandson, a most promising young Hexagon of unusual brilliancy and perfect angularity. His uncles and I had been giving him his usual practical lesson in Sight Recognition, turning ourselves upon our centres, now rapidly, now more slowly, and questioning him as to our positions; and his answers had been so satisfactory that I had been induced to reward him by giving him a few hints on Arithmetic, as applied to Geometry.

Taking nine Squares, each an inch every way, I had put them together so as to make one large Square, with a side of three inches, and I had hence proved to my little Grandson that --- though it was impossible for us to see the inside of the Square --- yet we might ascertain the number of square inches in a Square by simply squaring the number of inches in the side: "and thus," said I, "we know that 3◊sup{2}, or 9, represents the number of square inches in a Square whose side is 3 inches long."

The little Hexagon meditated on this a while and then said to me; "But you have been teaching me to raise numbers to the third power: I suppose 33 must mean something in Geometry; what does it mean?" "Nothing at all," replied I, "not at least in Geometry; for Geometry has only Two Dimensions." And then I began to shew the boy how a Point by moving through a length of three inches makes a Line of three inches, which may be represented by 3; and how a Line of three inches, moving parallel to itself through a length of three inches, makes a Square of three inches every way, which may be represented by 3◊sup{2}.

Upon this, my Grandson, again returning to his former suggestion, took me up rather suddenly and exclaimed, "Well, then, if a Point by moving three inches, makes a Line of three inches represented by 3; and if a straight Line of three inches, moving parallel to itself, makes a Square of three inches every way, represented by 3◊sup{2}; it must be that a Square of three inches every way, moving somehow parallel to itself (but I don't see how) must make Something else (but I don't see what) of three inches every way --- and this must be represented by 3◊sup{3}."

"Go to bed," said I, a little ruffled by this interruption: "if you would talk less nonsense, you would remember more sense."

So my Grandson had disappeared in disgrace; and there I sat by my Wife's side, endeavouring to form a retrospect of the year 1999 and of the possibilities of the year 2000, but not quite able to shake off the thoughts suggested by the prattle of my bright little Hexagon. Only a few sands now remained in the half-hour glass. Rousing myself from my reverie I turned the glass Northward for the last time in the old Millennium; and in the act, I exclaimed aloud, "The boy is a fool."

Straightway I became conscious of a Presence in the room, and a chilling breath thrilled through my very being. "He is no such thing," cried my Wife, "and you are breaking the Commandments in thus dishonouring your own Grandson." But I took no notice of her. Looking round in every direction I could see nothing; yet still I ◊emph{felt} a Presence, and shivered as the cold whisper came again. I started up. "What is the matter?" said my Wife, "there is no draught; what are you looking for? There is nothing." There was nothing; and I resumed my seat, again exclaiming, "The boy is a fool, I say; 3◊sup{3} can have no meaning in Geometry." At once there came a distinctly audible reply, "The boy is not a fool; and 3◊sup{3} has an obvious Geometrical meaning."

My Wife as well as myself heard the words, although she did not understand their meaning, and both of us sprang forward in the direction of the sound. What was our horror when we saw before us a Figure! At the first glance it appeared to be a Woman, seen sideways; but a moment's observation shewed me that the extremities passed into dimness too rapidly to represent one of the Female Sex; and I should have thought it a Circle, only that it seemed to change its size in a manner impossible for a Circle or for any regular Figure of which I had had experience.

But my Wife had not my experience, nor the coolness necessary to note these characteristics. With the usual hastiness and unreasoning jealousy of her Sex, she flew at once to the conclusion that a Woman had entered the house through some small aperture. "How comes this person here?" she exclaimed, "you promised me, my dear, that there should be no ventilators in our new house." "Nor are there any," said I; "but what makes you think that the stranger is a Woman? I see by my power of Sight Recognition --- " "Oh, I have no patience with your Sight Recognition," replied she, "'Feeling is believing' and 'A Straight Line to the touch is worth a Circle to the sight'” --- two Proverbs, very common with the Frailer Sex in Flatland.

"Well," said I, for I was afraid of irritating her, "if it must be so, demand an introduction." Assuming her most gracious manner, my Wife advanced towards the Stranger, "Permit me, Madam, to feel and be felt by --- " then, suddenly recoiling, "Oh! it is not a Woman, and there are no angles either, not a trace of one. Can it be that I have so misbehaved to a perfect Circle?"

"I am indeed, in a certain sense a Circle," replied the Voice, "and a more perfect Circle than any in Flatland, but to speak more accurately, I am many Circles in one." Then he added more mildly, "I have a message, dear Madam, to your husband, which I must not deliver in your presence; and, if you would suffer us to retire for a few minutes --- " But my Wife would not listen to the proposal that our august Visitor should so incommode himself, and assuring the Circle that the hour of her own retirement had long passed, with many reiterated apologies for her recent indiscretion, she at last retreated to her apartment.

I glanced at the half-hour glass. The last sands had fallen. The third Millennium had begun.
