#lang pollen

◊(define-meta chapter-num      "18")
◊(define-meta title            "How I came to Spaceland, and what I saw there.")
◊(define-meta doc-publish-date "25/08/2015")

◊newthought{An unspeakable} horror seized me. There was a darkness; then a dizzy, sickening sensation of sight that was not like seeing; I saw a Line that was no Line; Space that was not Space: I was myself, and not myself. When I could find voice, I shrieked aloud in agony, "Either this is madness or it is Hell." "It is neither," calmly replied the voice of the Sphere, "it is Knowledge; it is Three Dimensions: open your eye once again and try to look steadily."
I looked, and, behold, a new world! There stood before me, visibly incorporate, all that I had before inferred, conjectured, dreamed, of perfect Circular beauty. What seemed the centre of the Stranger's form lay open to my view: yet I could see no heart, nor lungs, nor arteries, only a beautiful harmonious Something --- for which I had no words; but you, my Readers in Spaceland, would call it the surface of the Sphere.

Prostrating myself mentally before my Guide, I cried, "How is it, O divine ideal of consummate loveliness and wisdom that I see thy inside, and yet cannot discern thy heart, thy lungs, thy arteries, thy liver?" "What you think you see, you see not," he replied; "it is not given to you, nor to any other Being to behold my internal parts. I am of a different order of Beings from those in Flatland. Were I a Circle, you could discern my intestines, but I am a Being, composed as I told you before, of many Circles, the Many in the One, called in this country a ◊i{Sphere.} And, just as the outside of a Cube is a Square, so the outside of a Sphere presents the appearance of a Circle."

Bewildered though I was by my Teacher's enigmatic utterance, I no longer chafed against it, but worshipped him in silent adoration. He continued, with more mildness in his voice. "Distress not yourself if you cannot at first understand the deeper mysteries of Spaceland. By degrees they will dawn upon you. Let us begin by casting back a glance at the region whence you came. Return with me a while to the plains of Flatland, and I will shew you that which you have often reasoned and thought about, but never seen with the sense of sight --- a visible angle." "Impossible!" I cried; but, the Sphere leading the way, I followed as if in a dream, till once more his voice arrested me: "Look yonder, and behold your own Pentagonal house, and all its inmates."

I looked below, and saw with my physical eye all that domestic individuality which I had hitherto merely inferred with the understanding. And how poor and shadowy was the inferred conjecture in comparison with the reality which I now beheld! ◊figure["img/ch18-fig01.png"]{ } My four Sons calmly asleep in the North-Western rooms, my two orphan Grandsons to the South; the Servants, the Butler, my Daughter, all in their several apartments. Only my affectionate Wife, alarmed by my continued absence, had quitted her room and was roving up and down in the Hall, anxiously awaiting my return. Also the Page, aroused by my cries, had left his room, and under pretext of ascertaining whether I had fallen somewhere in a faint, was prying into the cabinent in my study. All this I could now see, not merely infer; and as we came nearer and nearer, I could discern even the contents of my cabinet, and the two chests of gold and the tablets of which the sphere had made mention.

Touched by my Wife's distress, I would have sprung downward to reassure her, but I found myself incapable of motion. "Trouble not yurself about your Wife," said my Guide: "she will not be long left in anxiety; meantime let us take a survey of Flatland."

Once more I felt myself rising through space. It was even as the Sphere had said. The further we receded from the object we beheld, the larger became the field of vision. My native city, with the interior of every house and every creature therein, lay open to my view in minature. We mounted higher, and lo, the secrets of the earth, the depths of mines and intermost caverns of the hills, were bared before me.

Awestruck at the sight of the mysteries of the earth, thus unveiled before my unworthy eye, I said to my Companion, "Behold, I am become as a God. For the wise men in our country say that to see all things, or as they express it, ◊em{omnividence}, is the attribute of God alone." There was something of scorn in the voice of my Teacher as he made answer: "is it so indeed? Then the very pick-pockets and cut-throats of my country are to be worshiped by your wise men as being Gods: for there is not one of them that does not see as much as you see now. But trust me, your wise men are wrong."

◊i{I.} Then is omnividence the atribute of others besides Gods?

◊i{Sphere.} I do not know. But, if a pick-pocket or a cut-throat of our country can see everything that is in your country, surely that is no reason why the pick-pocket or cut-throat should be accepted by you as a God. this omnividence, as you call it --- it is not a common word in Spaceland --- does it make you more just, more merciful, less selfish, more loving? Not in the least. Then how does it make you more divine?

◊i{I.} "More merciful, more loving!" But these are the qualities of women! And we know that a Circle is a higher Being than a Straight Line, in so far as knowledge and wisdom are more to be esteemed than mere affection.

◊i{Sphere.} It is not for me to classify human faculties according to merit. Yet many of the best and wisest in Spaceland think more of the affections than of the understanding, more of your despised Straight Lines than of your belauded Circles. But enough of this. Look yonder. Do you know that building?

I looked, and afar off I saw an immense Polygonal structure, in which I recognized the General Assembly Hall of the States of Flatland, surrounded by dense lines of Pentagonal buildings at right angles to each other, which I knew to be streets; and I perceived that I was approaching the great Metropolis.

"Here we descend," said my Guide. It was now morning, the first hour of the first day of the two thousandth year of our era. Acting, as was their wont, in strict accordance with precedent, the highest Circles of the realm were meeting in solemn conclave, as they had met on the first hour of the first day of the year 1000, and also on the first hour of the first day of the year 0.

The minutes of the previous meetings were now read by one whom I at once recognized as my brother, a perfectly Symmetrical Square, and the Chief Clerk of the High Council. It was found recorded on each occasion that: "Whereas the States had been troubled by divers ill-intentioned persons pretending to have received revelations from another World, and professing to produce demonstrations whereby they had instigated to frenzy both themselves and others, it had been for this cause unanimously resolved by the Grand Council that on the first day of each millenary, special injunctions be sent to the Prefects in the several districts of Flatland, to make strict search for such misguided persons, and without formality of mathematical examination, to destroy all such as were Isosceles of any degree, to scourge and imprison any regular Triangle, to cause any Square or Pentagon to be sent to the district Asylum, and to arrest any one of higher rank, sending him straightway to the Capital to be examined and judged by the Council."

"You hear your fate," said the Sphere to me, while the Council was passing for the third time the formal resolution. "Death or imprisonment awaits the Apostle of the Gospel of Three Dimensions." "Not so," replied I, "the matter is now so clear to me, the nature of real space so palpable, that methinks I could make a child understand it. Permit me but to descend at this moment and enlighten them." "Not yet," said my Guide, "the time will come for that. Meantime I must perform my mission. Stay thou there in thy place." Saying these words, he leaped with great dexterity into the sea (if I may so call it) of Flatland, right in the midst of the ring of Counsellors. "I come," cried he, "to proclaim that there is a land of Three Dimensions."

I could see many of the younger Counsellors start back in manifest horror, as the Sphere's circular section widened before them. But on a sign from the presiding Circle --- who shewed not the slightest alarm or surprise --- six Isosceles of a low type from six different quarters rushed upon the Sphere. "We have him," they cried; "No; yes; we have him still! he's going! he's gone!"

"My Lords," said the President to the Junior Circles of the Council, "there is not the slightest need for surprise; the secret archives, to which I alone have access, tell me that a similar occurrence happened on the last two millennial commencements. You will, of course, say nothing of these trifles outside the Cabinet."

Raising his voice, he now summoned the guards. "Arrest the policemen; gag them. You know your duty." After he had consigned to their fate the wretched policemen --- ill-fated and unwilling witnesses of a State-secret which they were not to be permitted to reveal --- he again addressed the Counsellors. "My Lords, the business of the Council being concluded, I have only to wish you a happy New Year." Before departing, he expressed, at some length, to the Clerk, my excellent but most unfortunate brother, his sincere regret that, in accordance with precedent and for the sake of secrecy, he must condemn him to perpetual imprisonment, but added his satisfaction that, unless some mention were made by him of that day's incident, his life would be spared.
