#lang pollen

◊(define-meta chapter-num      "21")
◊(define-meta title            "How I tried to teach the theory of Three Dimensions to my Grandson, and with what success.")

◊newthought{I awoke} rejoicing, and began to reflect on the glorious career before me. I would go forth, methought, at once, and evangelize the whole of Flatland. Even to Women and Soldiers should the Gospel of Three Dimensions be proclaimed. I would begin with my Wife.

Just as I had decided on the plan of my operations, I heard the sound of many voices in the street commanding silence. Then followed a louder voice. It was a herald's proclamation. Listening attentively, I recognized the words of the Resolution of the Council, enjoining the arrest, imprisonment, or execution of any one who should pervert the minds of the people by delusions, and by professing to have received revelations from another World.

I reflected. This danger was not to be trifled with. It would be better to avoid it by omitting all mention of my Revelation, and by proceeding on the path of Demonstration --- which after all, seemed so simple and so conclusive that nothing would be lost by discarding the former means. "Upward, not Northward" --- was the clue to the whole proof. It had seemed to me fairly clear before I fell asleep; and when I first awoke, fresh from my dream, it had appeared as patent as Arithmetic; but somehow it did not seem to me quite so obvious now. Though my Wife entered the room opportunely just at that moment, I decided, after we had exchanged a few words of commonplace conversation, not to begin with her.

My Pentagonal Sons were men of character and standing, and physicians of no mean reputation, but not great in mathematics, and, in that respect, unfit for my purpose. But it occurred to me that a young and docile Hexagon, with a mathematical turn, would be a most suitable pupil. Why therefore not make my first experiment with my little precocious Grandson, whose casual remarks on the meaning of 3◊sup{3} had met with the approval of the Sphere? Discussing the matter with him, a mere boy, I should be in perfect safety; for he would know nothing of the Proclamation of the Council; whereas I could not feel sure that my Sons --- so greatly did their patriotism and reverence for the Circles predominate over mere blind affection --- might not feel compelled to hand me over to the Prefect, if they found me seriously maintaining the seditious heresy of the Third Dimension.

But the first thing to be done was to satisfy in some way the curiosity of my Wife, who naturally wished to know something of the reasons for which the Circle had desired that mysterious interview, and of the means by which he had entered the house. Without entering into the details of the elaborate account I gave her, --- an account, I fear, not quite so consistent with truth as my Readers in Spaceland might desire, --- I must be content with saying that I succeeded at last in persuading her to return quietly to her household duties without eliciting from me any reference to the World of Three Dimensions. This done, I immediately sent for my Grandson; for, to confess the truth, I felt that all that I had seen and heard was in some strange way slipping away from me, like the image of a half-grasped, tantalizing dream, and I longed to essay my skill in making a first disciple.

When my Grandson entered the room I carefully secured the door. Then, sitting down by his side and taking our mathematical tablets, --- or, as you would call them, Lines --- I told him we would resume the lesson of yesterday. I taught him once more how a Point by motion in One Dimension produces a Line, and how a straight Line in Two Dimensions produces a Square. After this, forcing a laugh, I said, "And now, you scamp, you wanted to make me believe that a Square may in the same way by motion Upward, not Northward' produce another figure, a sort of extra Square in Three Dimensions. Say that again, you young rascal."

At this moment we heard once more the herald's "O yes! O yes!" outside in the street proclaiming the Resolution of the Council. Young though he was, my Grandson --- who was unusually intelligent for his age, and bred up in perfect reverence for the authority of the Circles --- took in the situation with an acuteness for which I was quite unprepared. He remained silent till the last words of the Proclamation had died away, and then, bursting into tears, "Dear Grandpapa," he said, "that was only my fun, and of course I meant nothing at all by it; and we did not know anything then about the new Law; and I don't think I said anything about the Third Dimension; and I am sure I did not say one word about Upward, not Northward,' for that would be such nonsense, you know. How could a thing move Upward, and not Northward? Upward and not Northward! Even if I were a baby, I could not be so absurd as that. How silly it is! Ha! ha! ha!"

"Not at all silly," said I, losing my temper; "here for example, I take this Square," and, at the word, I grasped a moveable Square, which was lying at hand --- "and I move it, you see, not Northward but --- yes, I move it Upward --- that is to say, not Northward, but I move it somewhere --- not exactly like this, but somehow --- " Here I brought my sentence to an inane conclusion, shaking the Square about in a purposeless manner, much to the amusement of my Grandson, who burst out laughing louder than ever, and declared that I was not teaching him, but joking with him; and so saying he unlocked the door and ran out of the room. Thus ended my first attempt to convert a pupil to the Gospel of Three Dimensions.
