#lang pollen

◊(define-meta chapter-num      "22")
◊(define-meta title            "How I then tried to diffuse the Theory of Three Dimensions by other means, and of the result.")
◊(define-meta doc-publish-date "25/08/2015")

◊newthought{My failure} with my Grandson did not encourage me to communicate my secret to others of my household; yet neither was I led by it to despair of success. Only I saw that I must not wholly rely on the catch-phrase, "Upward, not Northward," but must rather endeavour to seek a demonstration by setting before the public a clear view of the whole subject; and for this purpose it seemed necessary to resort to writing.

So I devoted several months in privacy to the composition of a treatise on the mysteries of Three Dimensions. Only, with the view of evading the Law, if possible, I spoke not of a physical Dimension, but of a Thoughtland whence, in theory, a Figure could look down upon Flatland and see simultaneously the insides of all things, and where it was possible that there might be supposed to exist a Figure environed, as it were, with six Squares, and containing eight terminal Points. But in writing this book I found myself sadly hampered by the impossibility of drawing such diagrams as were necessary for my purpose; for of course, in our country of Flatland, there are no tablets but Lines, and no diagrams but Lines, all in one straight Line and only distinguishable by difference of size and brightness; so that, when I had finished my treatise (which I entitled, "Through Flatland to Thoughtland") I could not feel certain that many would understand my meaning.

Meanwhile my life was under a cloud. All pleasures palled upon me; all sights tantalized and tempted me to outspoken treason, because I could not but compare what I saw in Two Dimensions with what it really was if seen in Three, and could hardly refrain from making my comparisons aloud. I neglected my clients and my own business to give myself to the contemplation of the mysteries which I had once beheld, yet which I could impart to no one, and found daily more difficult to reproduce even before my own mental vision.

One day, about eleven months after my return from Spaceland, I tried to see a Cube with my eye closed, but failed; and though I succeeded afterwards, I was not then quite certain (nor have I been ever afterwards) that I had exactly realized the original. This made me more melancholy than before, and determined me to take some step; yet what, I knew not. I felt that I would have been willing to sacrifice my life for the Cause, if thereby I could have produced conviction. But if I could not convince my Grandson, how could I convince the highest and most developed Circles in the land?

And yet at times my spirit was too strong for me, and I gave vent to dangerous utterances. Already I was considered heterodox if not treasonable, and I was keenly alive to the danger of my position; nevertheless I could not at times refrain from bursting out into suspicious or half-seditious utterances, even among the highest Polygonal and Circular society. When, for example, the question arose about the treatment of those lunatics who said that they had received the power of seeing the insides of things, I would quote the saying of an ancient Circle, who declared that prophets and inspired people are always considered by the majority to be mad; and I could not help occasionally dropping such expressions as "the eye that discerns the interiors of things," and "the all-seeing land"; once or twice I even let fall the forbidden terms "the Third and Fourth Dimensions." At last, to complete a series of minor indiscretions, at a meeting of our Local Speculative Society held at the palace of the Prefect himself, --- some extremely silly person having read an elaborate paper exhibiting the precise reasons why Providence has limited the number of Dimensions to Two, and why the attribute of omnividence is assigned to the Supreme alone --- I so far forgot myself as to give an exact account of the whole of my voyage with the Sphere into Space, and to the Assembly Hall in our Metropolis, and then to Space again, and of my return home, and of everything that I had seen and heard in fact or vision. At first, indeed, I pretended that I was describing the imaginary experiences of a fictitious person; but my enthusiasm soon forced me to throw of all disguise, and finally, in a fervent peroration, I exhorted all my hearers to divest themselves of prejudice and to become believers in the Third Dimension.

Need I say that I was at once arrested and taken before the Council?

Next morning, standing in the very place where but a very few months ago the Sphere had stood in my company, I was allowed to begin and to continue my narration unquestioned and uninterrupted. But from the first I foresaw my fate; for the President, noting that a guard of the better sort of Policemen was in attendance, of angularity little, if at all, under 55°, ordered them to be relieved before I began my defence, by an inferior class of 2° or 3°. I knew only too well what that meant. I was to be executed or imprisoned, and my story was to be kept secret from the world by the simultaneous destruction of the officials who had heard it; and, this being the case, the President desired to substitute the cheaper for the more expensive victims.

After I had concluded my defence, the President, perhaps perceiving that some of the junior Circles had been moved by my evident earnestness, asked me two questions: ---

◊ol{
    ◊li{Whether I could indicate the direction which I meant when I used the words "Upward, not Northward"?}
    ◊li{Whether I could by any diagrams or descriptions (other than the enumeration of imaginary sides and angles) indicate the Figure I was pleased to call a Cube?}
}

I declared that I could say nothing more, and that I must commit myself to the Truth, whose cause would surely prevail in the end.

The President replied that he quite concurred in my sentiment, and that I could not do better. I must be sentenced to perpetual imprisonment; but if the Truth intended that I should emerge from prison and evangelize the world, the Truth might be trusted to bring that result to pass. Meanwhile I should be subjected to no discomfort that was not necessary to preclude escape, and, unless I forfeited the privilege by misconduct, I should be occasionally permitted to see my brother who had preceded me to my prison.

Seven years have elapsed and I am still a prisoner, and --- if I except the occasional visits of my brother --- debarred from all companionship save that of my jailers. My brother is one of the best of Squares, just, sensible, cheerful, and not without fraternal affection; yet I confess that my weekly interviews, at least in one respect, cause me the bitterest pain. He was present when the Sphere manifested himself in the Council Chamber; he saw the Sphere's changing sections; he heard the explanation of the phenomena then given to the Circles. Since that time, scarcely a week has passed during seven whole years, without his hearing from me a repetition of the part I played in that manifestation, together with ample descriptions of all the phenomena in Spaceland, and the arguments for the existence of Solid things derivable from Analogy. Yet --- I take shame to be forced to confess it --- my brother has not yet grasped the nature of the Third Dimension, and frankly avows his disbelief in the existence of a Sphere.

Hence I am absolutely destitute of converts, and, for aught that I can see, the millennial Revelation has been made to me for nothing. Prometheus up in Spaceland was bound for bringing down fire for mortals, but I --- poor Flatland Prometheus --- lie here in prison for bringing down nothing to my countrymen. Yet I exist in the hope that these memoirs, in some manner, I know not how, may find their way to the minds of humanity in Some Dimension, and may stir up a race of rebels who shall refuse to be confined to limited Dimensionality.

That is the hope of my brighter moments. Alas, it is not always so. Heavily weighs on me at times the burdensome reflection that I cannot honestly say I am confident as to the exact shape of the once-seen, oft-regretted Cube; and in my nightly visions the mysterious precept, "Upward, not Northward," haunts me like a soul-devouring Sphinx. It is part of the martyrdom which I endure for the cause of the Truth that there are seasons of mental weakness, when Cubes and Spheres flit away into the background of scarce-possible existences; when the Land of Three Dimensions seems almost as visionary as the Land of One or None; nay, when even this hard wall that bars me from my freedom, these very tablets on which I am writing, and all the substantial realities of Flatland itself, appear no better than the offspring of a diseased imagination, or the baseless fabric of a dream.

◊figure["img/ch22-fig01.png"]{}
